# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Student/Downloads/KGP_RISC/KGP_RISC.srcs/sources_1/ip/instr_memory/instr_memory.xci
# IP: The module: 'instr_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Downloads/KGP_RISC/KGP_RISC.srcs/sources_1/ip/instr_memory/instr_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Student/Downloads/KGP_RISC/KGP_RISC.srcs/sources_1/ip/instr_memory/instr_memory.xci
# IP: The module: 'instr_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Downloads/KGP_RISC/KGP_RISC.srcs/sources_1/ip/instr_memory/instr_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
