# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7vx690tffg1157-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.cache/wt} [current_project]
set_property parent.project_path {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Siddhartha/Course Work/Hardware Security/gcd/gcd.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/Mux.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/binar_gcd.srcs/sources_1/new/complementer.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/binar_gcd.srcs/sources_1/new/controlPath.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/binar_gcd.srcs/sources_1/new/input_Mux.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/binar_gcd.srcs/sources_1/new/lShift.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/binar_gcd.srcs/sources_1/new/rShift.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/new/register.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/substractor.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/new/up_down_counter.v}
  {C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/sources_1/imports/binary_gcd/binar_gcd.srcs/sources_1/new/gcd.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/constrs_1/new/timing.xdc}}
set_property used_in_implementation false [get_files {{C:/Siddhartha/Course Work/Hardware Security/gcd/gcd.srcs/constrs_1/new/timing.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top gcd -part xc7vx690tffg1157-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef gcd.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file gcd_utilization_synth.rpt -pb gcd_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
