# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/TA/2023_Autumn/BRAM_demo/BRAM_demo.srcs/sources_1/ip/bram_simp_dual/bram_simp_dual.xci
# IP: The module: 'bram_simp_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TA/2023_Autumn/BRAM_demo/BRAM_demo.srcs/sources_1/ip/bram_simp_dual/bram_simp_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_simp_dual'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/TA/2023_Autumn/BRAM_demo/BRAM_demo.srcs/sources_1/ip/bram_simp_dual/bram_simp_dual.xci
# IP: The module: 'bram_simp_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TA/2023_Autumn/BRAM_demo/BRAM_demo.srcs/sources_1/ip/bram_simp_dual/bram_simp_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_simp_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
